### ISSUE TITLE
after downloading the ember dataset . i am getting this error

### ISSUE THREAD

**Issue by varshinichowdary27** [tamnguyenvan/malnet#2]
X_train, y_train, X_test, y_test = ember.read_vectorized_features(data_dir, scale=args.scale)
  File "C:\Users\varshini\ember_dataset\malnet-master\src\ember\__init__.py", line 96, in read_vectorized_features
    X_train = np.memmap(X_train_path, dtype=np.float32, mode="r", shape=(int(scale * 900000), ndim))
  File "C:\Users\varshini\AppData\Local\Programs\Python\Python36\lib\site-packages\numpy\core\memmap.py", line 225, in __new__
    f_ctx = open(os_fspath(filename), ('r' if mode == 'c' else mode)+'b')
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\varshini\\ember_dataset\\malnet-master\\data\\X_train.dat'

**Comment by tamnguyenvan** [comment]
Cause there are no X_train.dat and y_train.dat. So you need follow the steps to reproduce the data.
1. Download dataset  [https://github.com/endgameinc/ember](Ember).
2. Extract features from the .json files
```
import ember
ember.create_vectorized_features("/data/ember/")
```
For more details, go to defination of the function and custom by yourself.
