### ISSUE TITLE
The training of data is taking long time

### ISSUE THREAD

**Issue by varshinichowdary27** [tamnguyenvan/malnet#3]
Training the data is not giving any output

![Screenshot (45)](https://user-images.githubusercontent.com/37653948/56133679-9fb48e00-5faa-11e9-9c32-648b9e890d3d.png)

**Comment by tamnguyenvan** [comment]
The dataset is large. So you should load a small number of samples first and try to train that one. I must use GPU GTX 1080 for training whole data. If you just have CPU, I will take long time

**Comment by varshinichowdary27** [comment]
For now, I have download ur model graph, pickle and h5 files and was Testing the model. Do you have any sample files for Testing

**Comment by tamnguyenvan** [comment]
Test data was evaluated right after training. Note that you must feed .exe file as input. Try other threshold value if need.

**Comment by varshinichowdary27** [comment]
okay,  I will try. (python src/test.py --input [path/to/sample/file] ) for this step  i need atleast 3 for my project.
Do u have any files.

**Comment by varshinichowdary27** [comment]
yeah got it by trying with other threshold value
