### ISSUE TITLE
Data Issue

### ISSUE THREAD

**Issue by ContegoCode** [tamnguyenvan/malnet#4]
You mention to make a data folder in the root directory and then left a link to download the data but the link has expired. Please can you update the download? I have tried and build the x_test and y_train files with ember with the 2018 data set but the files it creates seems to be to large and I receive a OS system out of resources error.

**Comment by tamnguyenvan** [comment]
Hi, I'll check it out and let you know.

Vào Th 2, 9 thg 3, 2020 vào lúc 14:42 ContegoCode <
notifications@github.com> đã viết:

**Comment by ContegoCode** [comment]
Thank you Every So much for the quick response and attention


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by ContegoCode** [comment]
Hey again if your able to get this running can I please know what you did. I have obtained images of virus files from kaggle but would you know of a source I can find beign file image datset ? Thank you for your time sir



Sent from my Samsung Galaxy smartphone.



-------- Original message --------

**Comment by tamnguyenvan** [comment]
Hey, @ContegoCode . I has updated this project. Please see README.md for the details.
