### ISSUE TITLE
Malware detection

### ISSUE THREAD

**Issue by potatoFry** [tamnguyenvan/malnet#8]
Hello, would just like to clarify doubts I have. The model detects malware solely through the grey scaled image of the malware yes? Sorry, am a bit confused due to the difference types of malnet available where some versions learn through the use of OP codes

**Comment by tamnguyenvan** [comment]
@potatoFry , the inputs of the model is a bunch of features which are extracted from PE file using Ember tool. I just concatenate them together and perform Conv1D.

**Comment by potatoFry** [comment]
Thank you for the explanation
