### ISSUE TITLE
Increase evaluation Speed

### ISSUE THREAD

**Issue by potatoFry** [tamnguyenvan/malnet#9]
Hey, currently takes the model about 30 minutes to go through 500 malware files. Any ideas to help increase the speed of the model detecting malware?

**Comment by tamnguyenvan** [comment]
Have you tried to run by batch?

**Comment by potatoFry** [comment]
I have written a script to run the command through a folder. Is there a separate method to pass the whole folder into the command which will make evaluation speed faster? I also believe that I am using CPU speed...

**Comment by tamnguyenvan** [comment]
Hi, the first thing is you need to make sure it's running on GPU for best performance. Secondly, you should change the code to run a batch of files once instead of running theme one by one.

**Comment by potatoFry** [comment]
Ok will do so. Thank you for your quick responses!
